name: 'TencentCloud CDN Action'
description: 'TencentCloud CDN Action'
author: 'suxuewb'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'upload-cloud'
  color: 'blue'

# Define your inputs here.
inputs:
  secret_id:
    description:
      'Tencent cloud secret id. Should be referred to a encrypted environment
      variable'
    required: true
  secret_key:
    description:
      'Tencent cloud secret key. Should be referred to a encrypted environment
      variable'
    required: true
  urls:
    description: 'The urls to purge'
  paths:
    description: 'The paths to purge'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
